title: Alchemy.js documentation site
source: app/docs/
destination: .tmp/docs/
exclude: [configuration/, misc/, styles/scss, js/coffee]

markdown: kramdown
# pygments: true
# highlighter: pygments
kramdown:
    toc_levels: 1..6
    use_coderay: true
    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      table
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               style

# defaults:
#   -
#     scope:
#       path: _documentation/ # an empty string here means all files in the project
#     values:
#       layout: "docsLayout"

collections:
- documentation