site_name: AlchemyDocs
docs_dir: 'app/docs'
site_dir: '.tmp/documentation'
pages:
- ['index.md', 'Getting Started']
- ['Configuration.md']
- ['GraphJSON.md', 'GraphJSON']
- ['Examples.md', 'Examples']
- ['Contributing.md', 'Contribute']

theme: readthedocs

